// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkgxnqdcdjabapptsqkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrZ3hucWRjZGphYmFwcHRzcWtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNjM1NzUsImV4cCI6MjA2MDczOTU3NX0.dxOpZOQzLmWUUjnVDxwFL4lx521mVKedoIZ0W8eNgxc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);